### ISSUE TITLE
Kotest Roadmap 4.1

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1089]
- [x] - Highlight diff when comparing data classes #826 #1242
- [x] - Arb.list doesn't use ListShrinker #1493
- [x] - Add Arb.choose that accepts weighted arbs #1499
- [x] - Add property test Arb for (lat, long) #1304
- [x] - Remove kotlintest aliases #1457
- [x] - Improve error message in tolerance matchers #1230
- [x] - Arb.bind<T>() calls the incorrect constructor #1487
- [x] - Integration with Testcontainers #1353
- [x] - Parent scopes are not coroutine scopes #1488
- [x] - `isolation` instead of `isolationMode` #1418
- [x] - Reflection equality improvements #1413
- [x] - Property tests should report exception of running shrunk input #1279
- [x] - x variants for Behavior / Feature / Expect spec #1383
- [x] - Add property test global config with before / after prop test callbacks #1435
- [x] - Parallel execution test cases in Spec #1362
- [x] - Project config dump doesn't include enums properly #1379
- [x] - Before\AfterProject catch only one Exception #1387
- [x] - Add `variable.assertSoftly` #1427
- [x] - Removed kotlintest aliases #1457 
- [x] - Coroutine helper for timeout #1447
- [x] - Add timeout to apply to individual tests when invocations > 1 #1442
- [x] - Add shouldExistInOrder matcher #1460
- [x] - Makes beforeProject and afterProject as suspend function #1461
- [x] - Add Missing documentation #1463
- [x] - Merge to an Exhausive of a superclass #1497
- [x] - Updated arb flat map to accept lists #1500
- [x] - Added Arb.orNull #1414
- [x] - test cases with multiline names broken #1441
- [x] - Date generators should allow for specific dates to be selected #1354
- [x] - Added Byte.shouldBeBetween(min, max) and Arb.bytes #1408 
- [x] - Provide a way to remove test prefixes in the test output when using specs which use prefixes #1486
- [x] - Filtering tests by tag happens after beforeSpec method is invoked #1516
- [x] - Release plugin.
