### ISSUE TITLE
Release 4.0.6

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1464]
- [x] - Compilation error when using kotest-assertions-core-jvm without kotest runner dependency #1425
- [x] - checkAll(Gen) for Exhaustive with large lists does not work #1456
- [x] - Any kind of `.show()` on `java.nio.file.Path` causes a StackOverflowError #1313

**Comment by ashishkujoy** [comment]
@sksamuel Do we need to anything for #1425 and #1313 as these issue seems to be resolve in snapshot version. 
A working test for those two issue. https://github.com/ashishkujoy/kotest-path-stackoverflow

**Comment by LeoColman** [comment]
@ashishkujoy Could you append your tests to our test base? If they pass I think it's a greenlight for those issues

**Comment by ashishkujoy** [comment]
@Kerooker we already have a passing test for that.
https://github.com/kotest/kotest/blob/master/kotest-assertions/kotest-assertions-shared/src/jvmTest/kotlin/com/sksamuel/kotest/show/PathShowTest.kt

**Comment by sksamuel** [comment]
I guess the #1313 fix was just never merged to the 4.0.6 branch then. I'll cherry pick that.

**Comment by sksamuel** [comment]
I've made a PR to add in the path.show fix from master.

**Comment by sksamuel** [comment]
#1425 is now ready in 4.0.6 as well. Once #1456 is merged I will release 4.0.6

**Comment by LeoColman** [comment]
Merged.

**Comment by sksamuel** [comment]
We're ready to release 4.0.6. Sonatype is having issues atm so I will try later.

**Comment by sksamuel** [comment]
4.0.6 has been released.
