### ISSUE TITLE
Kotest Roadmap 4.2

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1491]
- [x] - Bundle console runner with intellij plugin #1567
- [x] - Upgrade to Kotlin 1.4 #1511
- [x] - Change instance of matchers to use generic contracts #1510
- [x] - Control isolation mode by system property #1588
- [x] - Allow case control in test's reports #1458
- [x] - Use expression for tags instead of include/exclude #863
- [x] - Allow to disable SpringListener on final class warning #1573
- [x] - Add new scoped callbacks #1584
- [x] - Added exhaustive only mode to property tests #1596
- [x] - Support order annotation for SpecOrder #1593
- [x] - NoSuchFileException when using kotest-extensions-junitxml with Gradle #1581
- [x] - Non complete junit report when using FunSpec #999
- [x] - Improved error message for map should contain when key present #1587
- [x] - TestFactory listeners not executing on nested tests #1613
- [x] - prepareSpec and finalizeSpec don't work #1604
- [x] - shouldBeEqualToIgnoringFields behaviour is not consistent with shouldBe (equals) #1585
- [x] - Allow allure to be customizable #1527 
- [x] - Running all tests in a package doesn't run tests in subpackages #1621
- [x] - Can't run a single test method from Gradle 6.5 #1531
- [x] - Disabling test execution with x-methods doesn't work with kotest-core-js #1623
- [x] - Fix forAll(1) suspend parameters #1626
- [x] - Add matchers for Kotlinx.datetime #1628
- [x] - Allow multiple project configs to be detected and merged #1632
- [x] - Support timeout at leaf level #1551
- [x] - Support timeout/invocation timeouts via system properties #1631

**Comment by sksamuel** [comment]
4.2.0.RC1 released.

**Comment by sksamuel** [comment]
4.2.0 final released.
