### ISSUE TITLE
Kotest Roadmap 4.3

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1566]
- [x] Add steps and stack trace to allure, with full docs #460
- [x] Multi-line-string comparison for file contents #823
- [x] Support JUnit Test Extensions #1503
- [x] data driven tests with data classes #1537
- [x] Option to strip whitespace from test names #1545
- [x] Add Gen.forNone #1636
- [x] New assertion: Iterator.shouldHaveNext() #1660
- [x] New assertions: isEmpty / isDefined for java Optional #1661
- [x] Add property test gens for kotlinx datetime #1679
- [x] EnabledIf annotation for specs #1683
- [x] Combinatorial edgecases for Arb.flatMap and Arb.bind #1700
- [x] Add arb for big decimal #1705
- [x] Coroutine context from extensions is not propagated to tests #1725
- [x] Option to suppress configuration dump #1742
- [x] Non infix matchers should return this for easy chaining #1744
- [x] Created the severity attribute for TestCase with possibility to filter execution by severityLevel #1746
- [x] Make Engine dependency free #1748
- [x] Arb should generate a single value #1754
