### ISSUE TITLE
Roadmap 4.4

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1755]
- [x] Add Gen.lazy #1651
- [x] New map assertions #1697
- [x] Property test framework should support native #1747 
- [x] Improve parallelization of test suites #1760
- [x] Variation of clue / asClue to accept lazy #1766
- [x] New Map assertions shouldNotContainAnyKeysOf() shouldNotContainAnyValuesOf() #1769
- [x] Performance improvements for Exceptions on the JVM #1787
- [x] Add matchers for Atomic Booleans #1791
- [x] Upgrade to Kotlin 1.4.20 #1800 
- [x] Test cases should have their tags appended to the test name if so configured #1804
- [x] Removed superfluous whitespaces in freeSpec.kt #1819
- [x] Add functionality to use 'it' without surrounding 'describe' #1827
- [x] Using a symbol or Japanese etc in the test name will change the behavior #1828
- [x] Wrong behavior when combining assertSoftly and shouldNotBe #1831
- [x] Added inline version for intanceOf alias #1838
- [x] Add Support for globalAssertSoftly from System Property #1843
- [x] BehaviorSpec Then assertion shows green in Intellij but should show red #1857
- [x] Helper for temporary directory creation #1862 
- [x] AssertionMode.Error doesn't work on FeatureSpec #1864
- [x] Invalid test usage should throw at runtime #1882
- [x] Arb.list duplicated value as edgecase #1892
- [x] Output from reporters should be single threaded #1895
- [x] shouldBeBetween not defined for floats #1927
- [x] Support system properties through classpath based file #1928
- [x] Increase arity of checkall / forall property tests to 12 #1929
- [x] Arb.set with a range hangs the test if the given gen inside the set cannot produce enough values for the range #1931
- [x] Add more configurations to Email Generator #1941
- [x] not null matcher should show the value that was meant to be not null #1942
- [x] Add SpringTestExtension which exposes test context via coroutine context element #1956
- [x] Add active test extension #1959
- [x] Upgrade ktor matchers to use ktor 1.5 #1965
- [x] Allow data driven tests to register in root scope #1967
- [x] Add domain arbitrary #1969
- [x] Upgrade arrow matchers to 0.11.0 #1976
- [x] Spring test lifecycle callbacks do not work with constructor injection #1980
- [x] Enhance Json matchers #1984
- [x] Expand JSON matchers to support JS #1986
- [x] Add Arb.bind 11, 12, 13, 14 #1994
- [x] Disallow nested string scopes #2003
- [x] Replace jackson and js native with kotlinx-serialization json parsing in kotest-assertions #2004
- [x] Arb.bigInt always returns 0 #2013
- [x] Allow registration of custom Show typeclasses #2021
- [x] Note: min version is now 1.4

**Comment by sksamuel** [comment]
RC1 released.

**Comment by sksamuel** [comment]
4.4.0 released
