### ISSUE TITLE
Roadmap 4.5

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1913]
- [x] Add better mechanism for "or" in matchers #1950
- [x] Support objects for specs #1970
- [x] Generate HTML reports from JUnit XML #2011
- [x] Exhaustive cartesian #2119
- [x] Embedded kafka extension #2070
- [x] Wiremock extension #2071
- [x] Defer forAll nested blocks until runtime #2078
- [x] Kotest dependencies include kotlin standard library as dependencies but should make them as provided #2084
- [x] Arb composition through Arb.bind / Arb.flatMap should preserve edgecases #2095
- [x] kotest.tags should come from properties or environment #2098
- [x] Probabilistically use edge cases with random data instead of a cartesian product of all edge cases #2112
- [x] Add DayOfWeek assertions to Klock matchers #2113
- [x] Add a factory function to Matcher to simplify writing matchers #2114
- [x] Support multiplatform mobile for Klock assertions #2115
- [x] Exhaustive cartesian #2119
- [x] Improve shouldBe for collections #2121
- [x] Fixes Arb.bigdecimal getting hanged for min and max value which other than Double min and max #2135
- [x] Use the class name as the default prefix for temporary files / dirs #2140
- [x] System Exit Extension: Test fails though it should pass #2156
- [x] TestResult should have a reason why tests were skipped #2172
- [x] Arb.choose (the version taking Arbs) does not generate random values #2176
- [x] Change beEqualToIgnoringFields api to avoid runtime crashes #2183
- [x] Using checkAll, forAll and using take on an Arb cause an InvalidMutabilityException on XorWowRandom for Ios #2198
- [x] Fix issues of passing vararg to another function in containsInOrder #2200
- [x] Add watchos support back for x86 #2204
- [x] Shrinking of Arbs (String, and maybe others?) exceeds min size limit #2213
