### ISSUE TITLE
Roadmap 4.6

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2218]
- [x] Support config at spec, container and test level. #1370
- [x] test config is not recognized on tests run within a context #2050
- [x] Expanding config - style discussion #2065
- [x] Handle multiple exceptions in Kotlin Kotest eventually #2207
- [x] Upgrade to Kotlin 1.5 #2222
- [x] Add watchosX64 once coroutines is released #2069
- [x] Uniform way of providing test names for data-driven tests #2247

**Comment by mkotsbak** [comment]
Would it be possible to release a separate release with Kotlin 1.5.x support first, as Kotest seems to break upgrade of other code to Kotlin 1.5.x?

**Comment by sksamuel** [comment]
4.6 will basically be Kotlin 1.5 and whatever else is ready at the same time.
It won't be held up waiting for the above list.

**Comment by sksamuel** [comment]
We're targeting a release of 4.6 over the weekend to allow for upgrading to 1.5

**Comment by sksamuel** [comment]
4.6 has been released.
