### ISSUE TITLE
KotlinTest Roadmap 3.3

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#628]
Features and fixes for 3.3

- [x] - Intellij Plugin
- [x] - System properties and env extensions #623 #524
- [x] - Timezone and locale extensions #587
- [x] - Make "condensed" multi-line diffs configurable #607
- [x] - Security manager extension #624 
- [x] - New matchers and assertion improvements #616 #601 #603
- [x] - Arrow Extension - null support #611
- [x] - New Generators #530 #526 
- [x] - ExpectedException for AnnotationSpec #527
- [x] - Extended Word Spec
- [x] - Add project config option for `assertSoftly` #512 
- [x] - Disabled top level tests are not marked as ignored in JUnit #656
- [x] - Fail build if ignored tests option #644
- [ ] - Documentation for test filtering via gradle #597 
- [x] - Add support for PiTest #680
- [x] - Spring Listener support for mocks #684 
- [x] - Extend FunSpec to allows contexts #696
- [x] - Feature spec not enabling focus #699 
- [x] - Continually #643
- [x] - Digest matchers #667

**Comment by sksamuel** [comment]
I've like to release 3.3 as soon as possible because it's needed for the intellij plugin, which is by far the biggest feature. We can drop whatever we want to get it released.

**Comment by LeoColman** [comment]
Ok, keep `System Properties`, `Environment Extensions`, perhaps `Security Manager Extension` as it's code is mostly done at System Rules library.

I'm ok to keep only some of the new matchers, and drop the uninmplemented ones and improvements to a future release.

I don't see why we need to keep `Koin support`, `File management extension`, `Allow see and issue` and `Project config for assert softly`.

Not sure about retry helpers tho

**Comment by LeoColman** [comment]
System properties are done, Environment is very close done and Security Manager will probably follow these 2 examples

**Comment by sksamuel** [comment]
Ok I've bumped out those things.
If you can handle the two matcher tasks, and anything else you want, I will get the intellij plugin ready.

**Comment by LeoColman** [comment]
I think that with both Pull Requests being reviewed and approved, we're pretty much ready for this

**Comment by sksamuel** [comment]
Ok I believe the plugin is just about good to go, with some bugs to fix.
We can't do #612 you said, so lets have a quick look see what else we want to add in then we can release 3.3.0-RC1.

**Comment by LeoColman** [comment]
Can't we just go ahead and release what's on master? We're just missing documentation now

**Comment by sksamuel** [comment]
Can do, just seeing if there's any low hanging fruit we can add in a day.
Also, I need you (if you have time) to test the plugin with the remaining
specs then at least we can say it's good enough for a first release.
Basically, I just want to make sure I don't have to change kotlintest much
if there's a bug in the plugin.

**Comment by sksamuel** [comment]
Ok just #512 to be approved and #612 to be implemented or dropped, then I think we're good to release RC1.

**Comment by sksamuel** [comment]
I could sneak in #644 if you think it's a good feature while waiting on #184 to be tested.

**Comment by sksamuel** [comment]
#644 is in

**Comment by leoxs22** [comment]
Hey! I've been trying the new release to see if it's everything OK.

Not sure if this has something to do with this release, but when using the 3.3.0-RC2 version, I get this error:

`java.lang.UnsupportedClassVersionError: org/junit/jupiter/api/condition/EnabledIfSystemProperty has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
`

It doesn't happen when using the 3.2.1

It runs the tests anyway, it just appear as an initialization error, but it counts as a failed test:

![image](https://user-images.githubusercontent.com/9098977/52974290-c043db80-339f-11e9-80e1-acd8b773c910.png)

I've tried doing a mvn clean test, but it doesn't make any difference

Let me know if you need more information

**Comment by sksamuel** [comment]
Seems to be like the upgrade to JUnit Platform 1.4 has caused this. I guess they've compiled it with Java 11 and your runtime doesn't understand that.

I think we should downgrade to 1.3 like before - I didn't realize JUnit 1.4 was using JDK11.

@Kerooker thoughts?

**Comment by sksamuel** [comment]
Actually I think it's because *I* have compiled this with JDK11.
So I just need to re-release but make sure it compiles against JDK8.

**Comment by sksamuel** [comment]
It seems it only affect Java files (which that one is).

```
sam@sam-hp:~/development/workspace/kotlintest/kotlintest/kotlintest-core/build/classes/java/main/org/junit/jupiter/api/condition$ javap -verbose EnabledIfSystemProperty.class | grep "major"
  major version: 55
```

```
sam@sam-hp:~/development/workspace/kotlintest/kotlintest/kotlintest-core/build/classes/kotlin/main/io/kotlintest/internal$ javap -verbose ActiveKt.class | grep "major"
  major version: 50
```

**Comment by leoxs22** [comment]
Working perfectly now, thanks @sksamuel !

**Comment by sksamuel** [comment]
Great

**Comment by sksamuel** [comment]
3.3.0 has been released.
