### ISSUE TITLE
KotlinTest Roadmap 4.0

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#661]
Features and fixes for 4.0

**Rebrand**
- [x] - Update all docs to refer to new name
- [x] - Add typealias from io.kotlintest to io.kotest #1187
- [ ] - Blog / Article links for migration #1185
- [x] - Update logo #1171 
- [ ] - Order stickers and distribute
- [x] - Update kotlin-awesome to point to new org #1185
- [x] - Transfer repo to new org.

**Docs**
- [ ] - Document usage for Kotlin/JVM in Multiplatform projects #1105
- [ ] - Improve Property-based testing documentation #1152
- [x] - Documentation for test filtering via gradle #597
- [x] - Improve documentation on Listeners and Extensions #1118

**Framework improvements**
- [x] - Reuse specs, allow generic specs #598 #589
- [x] - Listener to run before/after a set of tests #458
- [x] - ProjectConfig should be auto-scanned #470
- [x] - Auto scan for project level extensions / listeners #1143
- [x] - FreeSpecScope String.config test function is not suspend #1085
- [x] - Enhance DescribeSpec with xMethods #763
- [x] - Focus and Bang are broken for DescribeSpec #1047
- [x] - Before/After Spec should allow coroutines #837
- [x] - Strip arrow `Try` from core #1090
- [x] - Project wide default test case config #1157
- [x] - Around test directly in the spec class #794
- [x] - Launching coroutine in test lambda does not attach to the correct scope #830
- [x] - Add function based enabledIf to test config #1166
- [x] - Confirm kotest does not bring in a logger #1052  #767 #639
- [x] - Configurable location of .kotlintest dir #849
- [x] - temp file handling #326 #1193
- [x] - removed invocations handling in favour of replay #721
- [x] - Support @Ignored at the spec level #1261
- [x] - Update eventually to return first error AND last error #1222
- [x] - Improve support for JUnit platform test discovery #1229
- [x] - After project failure "Class" #1234

**Multiplatform**
- [x] - Add support to Roboelectric #926
- [x] - Multi Platform - Kotlin JS #242

**Matchers**
- [x] - Comparator matchers #668
- [x] - New matcher: should be truthy #943
- [x] - Increasing/Decreasing list/seq matchers #850
- [x] - File matchers should implicitly check File.shouldExist #764
- [x] - Channel matchers #885
- [x] - Add regex matchers #1065
- [x] - Add jsoup matchers #1028
- [x] - Stats m#1098 rs #851
- [x] - shouldBeCalled assertion #1015
- [x] - String shouldbe UUID matcher #1119
- [x] - Integration with konform #1131
- [x] - Adding matcher to check a kotlin code compiles #1153
- [x] - Add forEachAsClue extension #939
- [x] - New matchers alias #933
- [x] - Create a matcher similar to Mockito's ReflectionEquals #1161
- [x] - Add Char Equivalent of IntMatchers #1113
- [x] - New collections matcher #1184 
- [x] - Add Matchers for kotlin durations #1207
- [x] - Collection comparison matcher should print missing and unexpected elements #1243
- [x] - ShouldThrowMessage #1269
- [x] - Path matchers should be implemented without a `toFile()` conversion #1272
- [x] - Add matchers to Klock #1156

**Test Helpers**
- [x] - Better toString with automatic support for Show for classes #662
- [x] - Inspectors are bugged when the message is very big #938
- [x] - forAll displays all errors at once, even when they are too many #929
- [x] - Eventually should be inline to support suspension #1098
- [x] - Retry Helpers #523
- [x] - Add allure annotations #1172
- [x] - Make eventually, until and continually cross platform #1183

**Extensions**
- [x] - Add mockserver extensions #1211
- [x] - Support http client in intellij #1197

**Property Testing**
- [x] - Allow min successful to be passed to property checks #780
- [x] - Property testing don't accept suspended lambdas #717
- [x] - Option to control Shrinking #967
- [x] - Must allow seeding of the random values in gens #815
- [x] - Unique modifier for Generators #971
- [x] - Property based tests for strings do not ever generate hieroglyphs #1088
- [x] - An exception in a property test doesn't show the failing values #1037
- [x] - Concat Gens #975
- [x] - Weight choose Generators #974
- [x] - Gen.file(dir) #947
- [x] - exhaustive generation option for property testing #969
- [x] - Add check coverage to prop testing #1198
- [x] - Add property test gen for emails #1134
- [x] - New generators #1120
- [x] - Generators for arrow types #701
- [x] - Print seed in prop tests #1201
- [x] - Add generator for js date #1204
- [x] - Add JS matcher for JS Date #1206
- [x] - Create generator that poll lines from a file #1100
- [x] - Generate data class using reflection in property tests #1245
- [x] - Property based tests for strings do not generate multi-code-unit graphemes #1088

**Compatibility**
- [x] - Generate junit report even when no tests #809
- [x] - Using SkipTestException causes error in JUnitTestRunnerListener #1034

**Comment by sksamuel** [comment]
Kotest 4.0 has been released.
