### ISSUE TITLE
KotlinTest Roadmap 3.4

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#788]
- [x] - Gradle Plugin Improvements #787
- [x] - io.kotlintest.Result conflicts with kotlin.Result #898
- [x] - Add support to Koin #515
- [x] - Global timeout #858
- [x] - Timeout config fails #879
- [x] - Allows nested describe scope #902
- [x] - Improved eventually #793 #781
- [x] - Added string matchers for single line and size between #853
- [x] - ShouldBeToday matcher #820
- [x] - Reflection Matchers #614 
- [x] - Modifies SpringListener to include Spring's Test Listeners #886
- [x] - LocalTime assertions #889
- [x] - Standard out and standard err wire listeners #708
- [x] - Add shouldBeNaN / shouldBePositiveInfinity matcher and so on #704 
- [x] - Limit parallelism #786
- [x] - Improvements to ProjectConfig output #877
- [x] - Improve matchers for throwables #810 #811
- [x] - Some new matchers to add #817
- [x] - New file matchers #838 #871
- [x] - Add matchers for Result #836
- [x] - Json Matchers from resources #873
- [x] - The URI matchers should also work on URLs. #818 
- [x] - ShouldBeZero matcher #819 
- [x] - Allow setting isolation mode in project config #842
- [x] - SkipTestException #522
- [x] - Standard out and standard err wire listeners #708
- [x] - between matcher for dates #665
- [x] - Improved arrow matchers #612 #802
- [x] - New matchers for BigDecimal: isZero, precision, scale, positive, negative #821
- [x] - Add mode to SystemEnvironmentProjectListener etc #829
- [x] - Allow setting isolation mode in project config #842
- [x] - beforeProject / afterProject in TestListener is confusing #859
- [x] - Add print statement for config #841
- [x] - Json Matchers from resources #873
- [x] - Add matchers for Result #836 
- [x] - use contracts for arrow matchers enhancement #802
- [x] - Multi line diff min line config option #706
- [x] - Better toString for output of values in tests #662
- [x] - Add matcher for Dates to ignore timezone #891

**Comment by sksamuel** [comment]
Looks like we should be ready to release in the coming days.
Saturday, if not before.

**Comment by lwasyl** [comment]
Now that 3.4 is released, is the list in this issue complete set of changes introduced? I see some issues that I reported so I'd guess yes, but I'm not sure. Asking since the latest changelog entry is 3.3.0

**Comment by LeoColman** [comment]
You're completely right. We didn't update the change log.

We are working on it and should release both a changelog and a blog post

**Comment by sksamuel** [comment]
Changelog is up.
