### ISSUE TITLE
KotlinTest Roadmap 3.5

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#827]
- [ ] - Multi-line-string comparison for file contents #823
- [ ] - Coroutine Matchers #813
- [ ] - Generators for arrow types #701
- [ ] - KotlinTestEngine does not obey JUnit5 extension points #799
- [ ] - Highlight diff when comparing data classes #826
- [ ] - Dependent tests #774
- [ ] - General improvements to property testing #815 #796 #780
- [ ] - Property testing don't accept suspended lambdas #717
- [ ] - Generate junit report even when no tests #809
- [ ] - Channel matchers #885
- [ ] - Flow Matchers
- [ ] - Further enhance Arrow matchers #709
- [ ] - Retry Helpers #523
- [ ] - Use expression for tags instead of include/exclude #863
- [ ] - New extension - profile #690
- [ ] - Gradle Plugin Failure Output Improvements #835
- [ ] - Increasing/Decreasing list/seq matchers #850

**Comment by sksamuel** [comment]
3.5 will be parked in favour of 4.0
