### ISSUE TITLE
KotlinTest 3.4.1 release

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#951]
Let's plan this release.

- [x] - Fail parent tests when child tests fail #935
- [x] - Fix Spring Boot JPA when using @DataJpaTest #950
- [x] - Remove  JUnit shadowed classes
- [x] - Update to Kotlin 1.3.50 #954

**Comment by LeoColman** [comment]
I didn't confirm this yet, but adding https://github.com/kotlintest/kotlintest/issues/950 is great too

**Comment by LeoColman** [comment]
Removing the JUnit shenanigans from our classpath seems very legit as well

**Comment by sksamuel** [comment]
Remind me on the junit - you removed the dummy annotations and added in the real ones ?

**Comment by sksamuel** [comment]
Released.
